// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playerservice.proto

#include "playerservice.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace playerservice {
PROTOBUF_CONSTEXPR PlayerServiceInitRequest::PlayerServiceInitRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.service_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerServiceInitRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerServiceInitRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerServiceInitRequestDefaultTypeInternal() {}
  union {
    PlayerServiceInitRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerServiceInitRequestDefaultTypeInternal _PlayerServiceInitRequest_default_instance_;
PROTOBUF_CONSTEXPR PlayerServiceInitResponse::PlayerServiceInitResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerServiceInitResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerServiceInitResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerServiceInitResponseDefaultTypeInternal() {}
  union {
    PlayerServiceInitResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerServiceInitResponseDefaultTypeInternal _PlayerServiceInitResponse_default_instance_;
}  // namespace playerservice
static ::_pb::Metadata file_level_metadata_playerservice_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_playerservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_playerservice_2eproto = nullptr;

const uint32_t TableStruct_playerservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::playerservice::PlayerServiceInitRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::playerservice::PlayerServiceInitRequest, _impl_.service_name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::playerservice::PlayerServiceInitResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::playerservice::PlayerServiceInitResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::playerservice::PlayerServiceInitResponse, _impl_.message_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::playerservice::PlayerServiceInitRequest)},
  { 7, -1, -1, sizeof(::playerservice::PlayerServiceInitResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::playerservice::_PlayerServiceInitRequest_default_instance_._instance,
  &::playerservice::_PlayerServiceInitResponse_default_instance_._instance,
};

const char descriptor_table_protodef_playerservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023playerservice.proto\022\rplayerservice\"0\n\030"
  "PlayerServiceInitRequest\022\024\n\014service_name"
  "\030\001 \001(\t\"=\n\031PlayerServiceInitResponse\022\017\n\007s"
  "uccess\030\001 \001(\010\022\017\n\007message\030\002 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_playerservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_playerservice_2eproto = {
    false, false, 157, descriptor_table_protodef_playerservice_2eproto,
    "playerservice.proto",
    &descriptor_table_playerservice_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_playerservice_2eproto::offsets,
    file_level_metadata_playerservice_2eproto, file_level_enum_descriptors_playerservice_2eproto,
    file_level_service_descriptors_playerservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_playerservice_2eproto_getter() {
  return &descriptor_table_playerservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_playerservice_2eproto(&descriptor_table_playerservice_2eproto);
namespace playerservice {

// ===================================================================

class PlayerServiceInitRequest::_Internal {
 public:
};

PlayerServiceInitRequest::PlayerServiceInitRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:playerservice.PlayerServiceInitRequest)
}
PlayerServiceInitRequest::PlayerServiceInitRequest(const PlayerServiceInitRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerServiceInitRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.service_name_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.service_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.service_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_service_name().empty()) {
    _this->_impl_.service_name_.Set(from._internal_service_name(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:playerservice.PlayerServiceInitRequest)
}

inline void PlayerServiceInitRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.service_name_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.service_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.service_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PlayerServiceInitRequest::~PlayerServiceInitRequest() {
  // @@protoc_insertion_point(destructor:playerservice.PlayerServiceInitRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerServiceInitRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.service_name_.Destroy();
}

void PlayerServiceInitRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerServiceInitRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:playerservice.PlayerServiceInitRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.service_name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerServiceInitRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string service_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_service_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "playerservice.PlayerServiceInitRequest.service_name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerServiceInitRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:playerservice.PlayerServiceInitRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string service_name = 1;
  if (!this->_internal_service_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_service_name().data(), static_cast<int>(this->_internal_service_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "playerservice.PlayerServiceInitRequest.service_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_service_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:playerservice.PlayerServiceInitRequest)
  return target;
}

size_t PlayerServiceInitRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:playerservice.PlayerServiceInitRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string service_name = 1;
  if (!this->_internal_service_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_service_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerServiceInitRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerServiceInitRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerServiceInitRequest::GetClassData() const { return &_class_data_; }


void PlayerServiceInitRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerServiceInitRequest*>(&to_msg);
  auto& from = static_cast<const PlayerServiceInitRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:playerservice.PlayerServiceInitRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_service_name().empty()) {
    _this->_internal_set_service_name(from._internal_service_name());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerServiceInitRequest::CopyFrom(const PlayerServiceInitRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:playerservice.PlayerServiceInitRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerServiceInitRequest::IsInitialized() const {
  return true;
}

void PlayerServiceInitRequest::InternalSwap(PlayerServiceInitRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.service_name_, lhs_arena,
      &other->_impl_.service_name_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerServiceInitRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_playerservice_2eproto_getter, &descriptor_table_playerservice_2eproto_once,
      file_level_metadata_playerservice_2eproto[0]);
}

// ===================================================================

class PlayerServiceInitResponse::_Internal {
 public:
};

PlayerServiceInitResponse::PlayerServiceInitResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:playerservice.PlayerServiceInitResponse)
}
PlayerServiceInitResponse::PlayerServiceInitResponse(const PlayerServiceInitResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerServiceInitResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.success_ = from._impl_.success_;
  // @@protoc_insertion_point(copy_constructor:playerservice.PlayerServiceInitResponse)
}

inline void PlayerServiceInitResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PlayerServiceInitResponse::~PlayerServiceInitResponse() {
  // @@protoc_insertion_point(destructor:playerservice.PlayerServiceInitResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerServiceInitResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void PlayerServiceInitResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerServiceInitResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:playerservice.PlayerServiceInitResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerServiceInitResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "playerservice.PlayerServiceInitResponse.message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerServiceInitResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:playerservice.PlayerServiceInitResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "playerservice.PlayerServiceInitResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:playerservice.PlayerServiceInitResponse)
  return target;
}

size_t PlayerServiceInitResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:playerservice.PlayerServiceInitResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerServiceInitResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerServiceInitResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerServiceInitResponse::GetClassData() const { return &_class_data_; }


void PlayerServiceInitResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerServiceInitResponse*>(&to_msg);
  auto& from = static_cast<const PlayerServiceInitResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:playerservice.PlayerServiceInitResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerServiceInitResponse::CopyFrom(const PlayerServiceInitResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:playerservice.PlayerServiceInitResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerServiceInitResponse::IsInitialized() const {
  return true;
}

void PlayerServiceInitResponse::InternalSwap(PlayerServiceInitResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.success_, other->_impl_.success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerServiceInitResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_playerservice_2eproto_getter, &descriptor_table_playerservice_2eproto_once,
      file_level_metadata_playerservice_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace playerservice
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::playerservice::PlayerServiceInitRequest*
Arena::CreateMaybeMessage< ::playerservice::PlayerServiceInitRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::playerservice::PlayerServiceInitRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::playerservice::PlayerServiceInitResponse*
Arena::CreateMaybeMessage< ::playerservice::PlayerServiceInitResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::playerservice::PlayerServiceInitResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
